// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demo.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const demoCreate = `-- name: DemoCreate :one
INSERT INTO demos (user_id, source, source_id, status, demo_file_id)
VALUES ($1, $2, $3, 'queued_parse', $4)
RETURNING id
`

type DemoCreateParams struct {
	UserID     int32
	Source     DemoSource
	SourceID   pgtype.Text
	DemoFileID pgtype.Text
}

func (q *Queries) DemoCreate(ctx context.Context, arg DemoCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, demoCreate,
		arg.UserID,
		arg.Source,
		arg.SourceID,
		arg.DemoFileID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const demoDelete = `-- name: DemoDelete :exec
UPDATE demos
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DemoDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, demoDelete, id)
	return err
}

const demoGet = `-- name: DemoGet :one
SELECT id, user_id, source, source_id, status, demo_file_id, created_at, status_updated_at, deleted_at
FROM demos
WHERE id = $1
`

func (q *Queries) DemoGet(ctx context.Context, id int32) (Demo, error) {
	row := q.db.QueryRow(ctx, demoGet, id)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.SourceID,
		&i.Status,
		&i.DemoFileID,
		&i.CreatedAt,
		&i.StatusUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const demoGetByUser = `-- name: DemoGetByUser :many
SELECT id, user_id, source, source_id, status, demo_file_id, created_at, status_updated_at, deleted_at
FROM demos
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) DemoGetByUser(ctx context.Context, userID int32) ([]Demo, error) {
	rows, err := q.db.Query(ctx, demoGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Demo
	for rows.Next() {
		var i Demo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.SourceID,
			&i.Status,
			&i.DemoFileID,
			&i.CreatedAt,
			&i.StatusUpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoUpdateFile = `-- name: DemoUpdateFile :exec
UPDATE demos
SET demo_file_id = $2
WHERE id = $1
`

type DemoUpdateFileParams struct {
	ID         int32
	DemoFileID pgtype.Text
}

func (q *Queries) DemoUpdateFile(ctx context.Context, arg DemoUpdateFileParams) error {
	_, err := q.db.Exec(ctx, demoUpdateFile, arg.ID, arg.DemoFileID)
	return err
}

const demoUpdateStatus = `-- name: DemoUpdateStatus :exec
UPDATE demos
SET status = $2, status_updated_at = NOW()
WHERE id = $1
`

type DemoUpdateStatusParams struct {
	ID     int32
	Status DemoStatus
}

func (q *Queries) DemoUpdateStatus(ctx context.Context, arg DemoUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, demoUpdateStatus, arg.ID, arg.Status)
	return err
}
