// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demo.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const demoCreate = `-- name: DemoCreate :one
INSERT INTO demos (source, source_id, source_url, status, file_id, played_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type DemoCreateParams struct {
	Source    DemoSource
	SourceID  string
	SourceUrl pgtype.Text
	Status    DemoStatus
	FileID    pgtype.Text
	PlayedAt  pgtype.Timestamptz
}

func (q *Queries) DemoCreate(ctx context.Context, arg DemoCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, demoCreate,
		arg.Source,
		arg.SourceID,
		arg.SourceUrl,
		arg.Status,
		arg.FileID,
		arg.PlayedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const demoGet = `-- name: DemoGet :one
SELECT id, source, source_id, source_url, file_id, data_id, status, attempts, error, played_at, status_updated_at, created_at
FROM demos
WHERE id = $1
`

func (q *Queries) DemoGet(ctx context.Context, id int32) (Demo, error) {
	row := q.db.QueryRow(ctx, demoGet, id)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.SourceUrl,
		&i.FileID,
		&i.DataID,
		&i.Status,
		&i.Attempts,
		&i.Error,
		&i.PlayedAt,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const demoGetBySourceSourceID = `-- name: DemoGetBySourceSourceID :one
SELECT id, source, source_id, source_url, file_id, data_id, status, attempts, error, played_at, status_updated_at, created_at
FROM demos
WHERE source = $1 AND source_id = $2
`

type DemoGetBySourceSourceIDParams struct {
	Source   DemoSource
	SourceID string
}

func (q *Queries) DemoGetBySourceSourceID(ctx context.Context, arg DemoGetBySourceSourceIDParams) (Demo, error) {
	row := q.db.QueryRow(ctx, demoGetBySourceSourceID, arg.Source, arg.SourceID)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.SourceUrl,
		&i.FileID,
		&i.DataID,
		&i.Status,
		&i.Attempts,
		&i.Error,
		&i.PlayedAt,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const demoGetByStatus = `-- name: DemoGetByStatus :many
SELECT id, source, source_id, source_url, file_id, data_id, status, attempts, error, played_at, status_updated_at, created_at
FROM demos
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) DemoGetByStatus(ctx context.Context, status DemoStatus) ([]Demo, error) {
	rows, err := q.db.Query(ctx, demoGetByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Demo
	for rows.Next() {
		var i Demo
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.SourceUrl,
			&i.FileID,
			&i.DataID,
			&i.Status,
			&i.Attempts,
			&i.Error,
			&i.PlayedAt,
			&i.StatusUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoGetByStatusUpdateAtomic = `-- name: DemoGetByStatusUpdateAtomic :many
WITH cte AS (
  SELECT d.id
  FROM demos d
  WHERE d.status = $2
  ORDER BY d.attempts, d.created_at
  FOR UPDATE SKIP LOCKED
  LIMIT $3
)
UPDATE demos
SET
  status = $1,
  error = NULL,
  attempts = attempts + 1,
  status_updated_at = NOW()
WHERE id in (SELECT id from cte)
RETURNING id, source, source_id, source_url, file_id, data_id, status, attempts, error, played_at, status_updated_at, created_at
`

type DemoGetByStatusUpdateAtomicParams struct {
	NewStatus DemoStatus
	OldStatus DemoStatus
	Amount    int32
}

func (q *Queries) DemoGetByStatusUpdateAtomic(ctx context.Context, arg DemoGetByStatusUpdateAtomicParams) ([]Demo, error) {
	rows, err := q.db.Query(ctx, demoGetByStatusUpdateAtomic, arg.NewStatus, arg.OldStatus, arg.Amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Demo
	for rows.Next() {
		var i Demo
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.SourceUrl,
			&i.FileID,
			&i.DataID,
			&i.Status,
			&i.Attempts,
			&i.Error,
			&i.PlayedAt,
			&i.StatusUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoGetByUserFiltered = `-- name: DemoGetByUserFiltered :many
SELECT
  d.id, d.source, d.source_id, d.source_url, d.file_id, d.data_id, d.status, d.attempts, d.error, d.played_at, d.status_updated_at, d.created_at,
  COUNT(*) OVER()::bigint AS total_count
FROM demos d
LEFT JOIN stats s ON s.demo_id = d.id
WHERE 
  (s.user_id = $3) AND
  (d.source = $4::DEMO_SOURCE OR NOT $5::bool)
ORDER BY d.played_at DESC
LIMIT $1 OFFSET $2
`

type DemoGetByUserFilteredParams struct {
	Limit        int32
	Offset       int32
	UserID       int32
	Source       DemoSource
	FilterSource bool
}

type DemoGetByUserFilteredRow struct {
	Demo       Demo
	TotalCount int64
}

func (q *Queries) DemoGetByUserFiltered(ctx context.Context, arg DemoGetByUserFilteredParams) ([]DemoGetByUserFilteredRow, error) {
	rows, err := q.db.Query(ctx, demoGetByUserFiltered,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Source,
		arg.FilterSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoGetByUserFilteredRow
	for rows.Next() {
		var i DemoGetByUserFilteredRow
		if err := rows.Scan(
			&i.Demo.ID,
			&i.Demo.Source,
			&i.Demo.SourceID,
			&i.Demo.SourceUrl,
			&i.Demo.FileID,
			&i.Demo.DataID,
			&i.Demo.Status,
			&i.Demo.Attempts,
			&i.Demo.Error,
			&i.Demo.PlayedAt,
			&i.Demo.StatusUpdatedAt,
			&i.Demo.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoResetStatusAll = `-- name: DemoResetStatusAll :exec
UPDATE demos
SET 
  status = $1,
  status_updated_at = NOW()
WHERE
  status = $2
`

type DemoResetStatusAllParams struct {
	NewStatus DemoStatus
	OldStatus DemoStatus
}

func (q *Queries) DemoResetStatusAll(ctx context.Context, arg DemoResetStatusAllParams) error {
	_, err := q.db.Exec(ctx, demoResetStatusAll, arg.NewStatus, arg.OldStatus)
	return err
}

const demoUpdateData = `-- name: DemoUpdateData :exec
UPDATE demos
SET data_id = $2
WHERE id = $1
`

type DemoUpdateDataParams struct {
	ID     int32
	DataID pgtype.Text
}

func (q *Queries) DemoUpdateData(ctx context.Context, arg DemoUpdateDataParams) error {
	_, err := q.db.Exec(ctx, demoUpdateData, arg.ID, arg.DataID)
	return err
}

const demoUpdateFile = `-- name: DemoUpdateFile :exec
UPDATE demos
SET file_id = $2
WHERE id = $1
`

type DemoUpdateFileParams struct {
	ID     int32
	FileID pgtype.Text
}

func (q *Queries) DemoUpdateFile(ctx context.Context, arg DemoUpdateFileParams) error {
	_, err := q.db.Exec(ctx, demoUpdateFile, arg.ID, arg.FileID)
	return err
}

const demoUpdateStatus = `-- name: DemoUpdateStatus :exec
UPDATE demos
SET
  status = $2,
  error = $3,
  attempts = $4,
  status_updated_at = NOW()
WHERE id = $1
`

type DemoUpdateStatusParams struct {
	ID       int32
	Status   DemoStatus
	Error    pgtype.Text
	Attempts int32
}

func (q *Queries) DemoUpdateStatus(ctx context.Context, arg DemoUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, demoUpdateStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.Attempts,
	)
	return err
}
