// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: highlight.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const highlightCreate = `-- name: HighlightCreate :one
INSERT INTO highlights (user_id, demo_id, title)
VALUES ($1, $2, $3)
RETURNING id
`

type HighlightCreateParams struct {
	UserID int32
	DemoID int32
	Title  string
}

func (q *Queries) HighlightCreate(ctx context.Context, arg HighlightCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, highlightCreate, arg.UserID, arg.DemoID, arg.Title)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const highlightDeleteFile = `-- name: HighlightDeleteFile :exec
UPDATE highlights
SET file_id = NULL, file_web_id = NULL
WHERE id = $1
`

func (q *Queries) HighlightDeleteFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, highlightDeleteFile, id)
	return err
}

const highlightGetByDemo = `-- name: HighlightGetByDemo :many
SELECT id, user_id, demo_id, file_id, file_web_id, title, created_at
FROM highlights
WHERE demo_id = $1
ORDER BY created_at
`

func (q *Queries) HighlightGetByDemo(ctx context.Context, demoID int32) ([]Highlight, error) {
	rows, err := q.db.Query(ctx, highlightGetByDemo, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DemoID,
			&i.FileID,
			&i.FileWebID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const highlightUpdate = `-- name: HighlightUpdate :exec
UPDATE highlights
SET 
  demo_id = coalesce($2, demo_id),
  file_id = coalesce($3, file_id),
  file_web_id = coalesce($4, file_web_id),
  title = coalesce($5, title)
WHERE id = $1
`

type HighlightUpdateParams struct {
	ID        int32
	DemoID    pgtype.Int4
	FileID    pgtype.Text
	FileWebID pgtype.Text
	Title     pgtype.Text
}

func (q *Queries) HighlightUpdate(ctx context.Context, arg HighlightUpdateParams) error {
	_, err := q.db.Exec(ctx, highlightUpdate,
		arg.ID,
		arg.DemoID,
		arg.FileID,
		arg.FileWebID,
		arg.Title,
	)
	return err
}
