// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: highlight.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const highlightCreate = `-- name: HighlightCreate :one
INSERT INTO highlights (demo_id, file_id, title)
VALUES ($1, $2, $3)
RETURNING id
`

type HighlightCreateParams struct {
	DemoID int32
	FileID pgtype.Text
	Title  string
}

func (q *Queries) HighlightCreate(ctx context.Context, arg HighlightCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, highlightCreate, arg.DemoID, arg.FileID, arg.Title)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const highlightUpdateFile = `-- name: HighlightUpdateFile :exec
UPDATE highlights
SET file_id = $2
WHERE id = $1
`

type HighlightUpdateFileParams struct {
	ID     int32
	FileID pgtype.Text
}

func (q *Queries) HighlightUpdateFile(ctx context.Context, arg HighlightUpdateFileParams) error {
	_, err := q.db.Exec(ctx, highlightUpdateFile, arg.ID, arg.FileID)
	return err
}
