// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: highlight_segment.sql

package sqlc

import (
	"context"
)

const highlightSegmentCreate = `-- name: HighlightSegmentCreate :one
INSERT INTO highlight_segments (highlight_id, start_tick, end_tick)
VALUES ($1, $2, $3)
RETURNING id
`

type HighlightSegmentCreateParams struct {
	HighlightID int32
	StartTick   int32
	EndTick     int32
}

func (q *Queries) HighlightSegmentCreate(ctx context.Context, arg HighlightSegmentCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, highlightSegmentCreate, arg.HighlightID, arg.StartTick, arg.EndTick)
	var id int32
	err := row.Scan(&id)
	return id, err
}
