// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DemoSource string

const (
	DemoSourceManual DemoSource = "manual"
	DemoSourceSteam  DemoSource = "steam"
	DemoSourceFaceit DemoSource = "faceit"
)

func (e *DemoSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DemoSource(s)
	case string:
		*e = DemoSource(s)
	default:
		return fmt.Errorf("unsupported scan type for DemoSource: %T", src)
	}
	return nil
}

type NullDemoSource struct {
	DemoSource DemoSource
	Valid      bool // Valid is true if DemoSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDemoSource) Scan(value interface{}) error {
	if value == nil {
		ns.DemoSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DemoSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDemoSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DemoSource), nil
}

type DemoStatus string

const (
	DemoStatusQueuedParse    DemoStatus = "queued_parse"
	DemoStatusParsing        DemoStatus = "parsing"
	DemoStatusQueuedRender   DemoStatus = "queued_render"
	DemoStatusRendering      DemoStatus = "rendering"
	DemoStatusQueuedFinalize DemoStatus = "queued_finalize"
	DemoStatusFinalizing     DemoStatus = "finalizing"
	DemoStatusFinished       DemoStatus = "finished"
	DemoStatusFailed         DemoStatus = "failed"
)

func (e *DemoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DemoStatus(s)
	case string:
		*e = DemoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DemoStatus: %T", src)
	}
	return nil
}

type NullDemoStatus struct {
	DemoStatus DemoStatus
	Valid      bool // Valid is true if DemoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDemoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DemoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DemoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDemoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DemoStatus), nil
}

type Result string

const (
	ResultWin  Result = "win"
	ResultLoss Result = "loss"
	ResultTie  Result = "tie"
)

func (e *Result) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Result(s)
	case string:
		*e = Result(s)
	default:
		return fmt.Errorf("unsupported scan type for Result: %T", src)
	}
	return nil
}

type NullResult struct {
	Result Result
	Valid  bool // Valid is true if Result is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResult) Scan(value interface{}) error {
	if value == nil {
		ns.Result, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Result.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Result), nil
}

type Team string

const (
	TeamCt Team = "ct"
	TeamT  Team = "t"
)

func (e *Team) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Team(s)
	case string:
		*e = Team(s)
	default:
		return fmt.Errorf("unsupported scan type for Team: %T", src)
	}
	return nil
}

type NullTeam struct {
	Team  Team
	Valid bool // Valid is true if Team is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeam) Scan(value interface{}) error {
	if value == nil {
		ns.Team, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Team.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeam) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Team), nil
}

type Demo struct {
	ID              int32
	Source          DemoSource
	SourceID        pgtype.Text
	FileID          pgtype.Text
	DataID          pgtype.Text
	Status          DemoStatus
	Attempts        int32
	Error           pgtype.Text
	StatusUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type Highlight struct {
	ID        int32
	UserID    int32
	DemoID    int32
	FileID    pgtype.Text
	Title     string
	Round     int32
	DurationS int32
	CreatedAt pgtype.Timestamptz
}

type HighlightSegment struct {
	ID          int32
	HighlightID int32
	StartTick   int32
	EndTick     int32
}

type Stat struct {
	ID        int32
	DemoID    int32
	UserID    int32
	Result    NullResult
	StartTeam NullTeam
	Kills     pgtype.Int4
	Assists   pgtype.Int4
	Deaths    pgtype.Int4
}

type StatsDemo struct {
	ID       int32
	DemoID   int32
	Map      pgtype.Text
	RoundsCt pgtype.Int4
	RoundsT  pgtype.Int4
}

type User struct {
	ID          int32
	Uid         int32
	Name        pgtype.Text
	DisplayName string
	AvatarUrl   pgtype.Text
	Crosshair   pgtype.Text
	Admin       bool
}
