// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const settingUserCreate = `-- name: SettingUserCreate :one
INSERT INTO setting_user (user_id, steam_match_token, steam_import_old, steam_authentication_token, faceit_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type SettingUserCreateParams struct {
	UserID                   int32
	SteamMatchToken          pgtype.Text
	SteamImportOld           pgtype.Bool
	SteamAuthenticationToken pgtype.Text
	FaceitID                 pgtype.Text
}

func (q *Queries) SettingUserCreate(ctx context.Context, arg SettingUserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, settingUserCreate,
		arg.UserID,
		arg.SteamMatchToken,
		arg.SteamImportOld,
		arg.SteamAuthenticationToken,
		arg.FaceitID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const settingUserGetByUser = `-- name: SettingUserGetByUser :one
SELECT id, user_id, steam_match_token, steam_authentication_token, steam_import_old, faceit_id, first_time_wizard
FROM setting_user
WHERE user_id = $1
`

func (q *Queries) SettingUserGetByUser(ctx context.Context, userID int32) (SettingUser, error) {
	row := q.db.QueryRow(ctx, settingUserGetByUser, userID)
	var i SettingUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SteamMatchToken,
		&i.SteamAuthenticationToken,
		&i.SteamImportOld,
		&i.FaceitID,
		&i.FirstTimeWizard,
	)
	return i, err
}

const settingUserUpdate = `-- name: SettingUserUpdate :exec
UPDATE setting_user
SET
  steam_match_token = $2,
  steam_authentication_token = $3,
  steam_import_old = $4,
  faceit_id = $5,
  first_time_wizard = $6
WHERE id = $1
`

type SettingUserUpdateParams struct {
	ID                       int32
	SteamMatchToken          pgtype.Text
	SteamAuthenticationToken pgtype.Text
	SteamImportOld           pgtype.Bool
	FaceitID                 pgtype.Text
	FirstTimeWizard          bool
}

func (q *Queries) SettingUserUpdate(ctx context.Context, arg SettingUserUpdateParams) error {
	_, err := q.db.Exec(ctx, settingUserUpdate,
		arg.ID,
		arg.SteamMatchToken,
		arg.SteamAuthenticationToken,
		arg.SteamImportOld,
		arg.FaceitID,
		arg.FirstTimeWizard,
	)
	return err
}
