// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting_global.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const settingGlobalGet = `-- name: SettingGlobalGet :one
SELECT id, demo_upload, custom_criteria, chat_command, chat_trigger
FROM setting_global
WHERE id = 1
`

func (q *Queries) SettingGlobalGet(ctx context.Context) (SettingGlobal, error) {
	row := q.db.QueryRow(ctx, settingGlobalGet)
	var i SettingGlobal
	err := row.Scan(
		&i.ID,
		&i.DemoUpload,
		&i.CustomCriteria,
		&i.ChatCommand,
		&i.ChatTrigger,
	)
	return i, err
}

const settingGlobalUpdate = `-- name: SettingGlobalUpdate :exec
UPDATE setting_global
SET
  demo_upload = coalesce($1, demo_upload),
  custom_criteria = coalesce($2, custom_criteria),
  chat_command = coalesce($3, chat_command),
  chat_trigger = coalesce($4, chat_trigger)
WHERE id = 1
`

type SettingGlobalUpdateParams struct {
	DemoUpload     pgtype.Bool
	CustomCriteria pgtype.Bool
	ChatCommand    pgtype.Bool
	ChatTrigger    pgtype.Text
}

func (q *Queries) SettingGlobalUpdate(ctx context.Context, arg SettingGlobalUpdateParams) error {
	_, err := q.db.Exec(ctx, settingGlobalUpdate,
		arg.DemoUpload,
		arg.CustomCriteria,
		arg.ChatCommand,
		arg.ChatTrigger,
	)
	return err
}
