// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stat.sql

package sqlc

import (
	"context"
)

const statCreate = `-- name: StatCreate :one
INSERT INTO stats (demo_id, user_id, result, start_team, kills, assists, deaths)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type StatCreateParams struct {
	DemoID    int32
	UserID    int32
	Result    Result
	StartTeam Team
	Kills     int32
	Assists   int32
	Deaths    int32
}

func (q *Queries) StatCreate(ctx context.Context, arg StatCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, statCreate,
		arg.DemoID,
		arg.UserID,
		arg.Result,
		arg.StartTeam,
		arg.Kills,
		arg.Assists,
		arg.Deaths,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const statGetByDemos = `-- name: StatGetByDemos :many
SELECT id, demo_id, user_id, result, start_team, kills, assists, deaths
FROM stats
WHERE demo_id = ANY($1::int[])
`

func (q *Queries) StatGetByDemos(ctx context.Context, dollar_1 []int32) ([]Stat, error) {
	rows, err := q.db.Query(ctx, statGetByDemos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.UserID,
			&i.Result,
			&i.StartTeam,
			&i.Kills,
			&i.Assists,
			&i.Deaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
