// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats_demo.sql

package sqlc

import (
	"context"
)

const statsDemoCreate = `-- name: StatsDemoCreate :one
INSERT INTO stats_demos (demo_id, map, rounds_ct, rounds_t)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type StatsDemoCreateParams struct {
	DemoID   int32
	Map      string
	RoundsCt int32
	RoundsT  int32
}

func (q *Queries) StatsDemoCreate(ctx context.Context, arg StatsDemoCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, statsDemoCreate,
		arg.DemoID,
		arg.Map,
		arg.RoundsCt,
		arg.RoundsT,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
