// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stat.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const statCreate = `-- name: StatCreate :one
INSERT INTO stats (demo_id, user_id, result, start_team, kills, assists, deaths)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type StatCreateParams struct {
	DemoID    int32
	UserID    int32
	Result    NullResult
	StartTeam NullTeam
	Kills     pgtype.Int4
	Assists   pgtype.Int4
	Deaths    pgtype.Int4
}

func (q *Queries) StatCreate(ctx context.Context, arg StatCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, statCreate,
		arg.DemoID,
		arg.UserID,
		arg.Result,
		arg.StartTeam,
		arg.Kills,
		arg.Assists,
		arg.Deaths,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const statGetByDemo = `-- name: StatGetByDemo :many
SELECT id, demo_id, user_id, result, start_team, kills, assists, deaths
FROM stats
WHERE demo_id = $1
`

func (q *Queries) StatGetByDemo(ctx context.Context, demoID int32) ([]Stat, error) {
	rows, err := q.db.Query(ctx, statGetByDemo, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.UserID,
			&i.Result,
			&i.StartTeam,
			&i.Kills,
			&i.Assists,
			&i.Deaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statGetByDemos = `-- name: StatGetByDemos :many
SELECT id, demo_id, user_id, result, start_team, kills, assists, deaths
FROM stats
WHERE demo_id = ANY($1::int[])
`

func (q *Queries) StatGetByDemos(ctx context.Context, dollar_1 []int32) ([]Stat, error) {
	rows, err := q.db.Query(ctx, statGetByDemos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.UserID,
			&i.Result,
			&i.StartTeam,
			&i.Kills,
			&i.Assists,
			&i.Deaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statUpdate = `-- name: StatUpdate :exec
UPDATE stats
SET result = $2, start_team = $3, kills = $4, assists = $5, deaths = $6
WHERE id = $1
`

type StatUpdateParams struct {
	ID        int32
	Result    NullResult
	StartTeam NullTeam
	Kills     pgtype.Int4
	Assists   pgtype.Int4
	Deaths    pgtype.Int4
}

func (q *Queries) StatUpdate(ctx context.Context, arg StatUpdateParams) error {
	_, err := q.db.Exec(ctx, statUpdate,
		arg.ID,
		arg.Result,
		arg.StartTeam,
		arg.Kills,
		arg.Assists,
		arg.Deaths,
	)
	return err
}
