// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats_demo.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const statsDemoCreate = `-- name: StatsDemoCreate :one
INSERT INTO stats_demos (demo_id, map, rounds_ct, rounds_t)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type StatsDemoCreateParams struct {
	DemoID   int32
	Map      pgtype.Text
	RoundsCt pgtype.Int4
	RoundsT  pgtype.Int4
}

func (q *Queries) StatsDemoCreate(ctx context.Context, arg StatsDemoCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, statsDemoCreate,
		arg.DemoID,
		arg.Map,
		arg.RoundsCt,
		arg.RoundsT,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const statsDemoGetByDemo = `-- name: StatsDemoGetByDemo :one
SELECT id, demo_id, map, rounds_ct, rounds_t
FROM stats_demos
WHERE demo_id = $1
`

func (q *Queries) StatsDemoGetByDemo(ctx context.Context, demoID int32) (StatsDemo, error) {
	row := q.db.QueryRow(ctx, statsDemoGetByDemo, demoID)
	var i StatsDemo
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.Map,
		&i.RoundsCt,
		&i.RoundsT,
	)
	return i, err
}

const statsDemoGetByDemos = `-- name: StatsDemoGetByDemos :many
SELECT id, demo_id, map, rounds_ct, rounds_t
FROM stats_demos
WHERE demo_id = ANY($1::int[])
`

func (q *Queries) StatsDemoGetByDemos(ctx context.Context, dollar_1 []int32) ([]StatsDemo, error) {
	rows, err := q.db.Query(ctx, statsDemoGetByDemos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsDemo
	for rows.Next() {
		var i StatsDemo
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.Map,
			&i.RoundsCt,
			&i.RoundsT,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsDemoUpdate = `-- name: StatsDemoUpdate :exec
UPDATE stats_demos
SET map = $2, rounds_ct = $3, rounds_ct = $4, rounds_t = $5
WHERE id = $1
`

type StatsDemoUpdateParams struct {
	ID         int32
	Map        pgtype.Text
	RoundsCt   pgtype.Int4
	RoundsCt_2 pgtype.Int4
	RoundsT    pgtype.Int4
}

func (q *Queries) StatsDemoUpdate(ctx context.Context, arg StatsDemoUpdateParams) error {
	_, err := q.db.Exec(ctx, statsDemoUpdate,
		arg.ID,
		arg.Map,
		arg.RoundsCt,
		arg.RoundsCt_2,
		arg.RoundsT,
	)
	return err
}
