// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stat.sql

package sqlc

import (
	"context"
)

const statCreate = `-- name: StatCreate :one
INSERT INTO stats (demo_id, user_id, kills, assists, deaths)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type StatCreateParams struct {
	DemoID  int32
	UserID  int32
	Kills   int32
	Assists int32
	Deaths  int32
}

func (q *Queries) StatCreate(ctx context.Context, arg StatCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, statCreate,
		arg.DemoID,
		arg.UserID,
		arg.Kills,
		arg.Assists,
		arg.Deaths,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
