// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userCreate = `-- name: UserCreate :one
INSERT INTO users (uid, name, display_name, avatar_url, crosshair, admin)
VALUES ($1, $2, $3, $4, $5, NOT EXISTS (SELECT 1 FROM users))
RETURNING id
`

type UserCreateParams struct {
	Uid         int32
	Name        pgtype.Text
	DisplayName string
	AvatarUrl   pgtype.Text
	Crosshair   pgtype.Text
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, userCreate,
		arg.Uid,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Crosshair,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userGet = `-- name: UserGet :one
SELECT id, uid, name, display_name, avatar_url, crosshair, admin
FROM users
WHERE id = $1
`

func (q *Queries) UserGet(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Crosshair,
		&i.Admin,
	)
	return i, err
}

const userGetAdmin = `-- name: UserGetAdmin :many
SELECT id, uid, name, display_name, avatar_url, crosshair, admin
FROM users
WHERE admin
`

func (q *Queries) UserGetAdmin(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, userGetAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Crosshair,
			&i.Admin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userGetByIds = `-- name: UserGetByIds :many
SELECT id, uid, name, display_name, avatar_url, crosshair, admin
FROM users
WHERE id = ANY($1::int[])
`

func (q *Queries) UserGetByIds(ctx context.Context, dollar_1 []int32) ([]User, error) {
	rows, err := q.db.Query(ctx, userGetByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Crosshair,
			&i.Admin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userGetByUid = `-- name: UserGetByUid :one
SELECT id, uid, name, display_name, avatar_url, crosshair, admin
FROM users
WHERE uid = $1
`

func (q *Queries) UserGetByUid(ctx context.Context, uid int32) (User, error) {
	row := q.db.QueryRow(ctx, userGetByUid, uid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Crosshair,
		&i.Admin,
	)
	return i, err
}

const userGetFiltered = `-- name: UserGetFiltered :many
SELECT
  u.id, u.uid, u.name, u.display_name, u.avatar_url, u.crosshair, u.admin,
  COUNT(*) OVER()::bigint AS total_count
FROM users u
WHERE
  (u.name ILIKE '%' || $3::text || '%' OR u.display_name ILIKE '%' || $3::text || '%') AND
  (u.admin = $4::bool OR NOT $5::bool) AND
  (u.name != '' OR NOT $6::bool)
ORDER BY u.name, u.display_name
LIMIT $1 OFFSET $2
`

type UserGetFilteredParams struct {
	Limit       int32
	Offset      int32
	Name        string
	Admin       bool
	FilterAdmin bool
	FilterReal  bool
}

type UserGetFilteredRow struct {
	User       User
	TotalCount int64
}

func (q *Queries) UserGetFiltered(ctx context.Context, arg UserGetFilteredParams) ([]UserGetFilteredRow, error) {
	rows, err := q.db.Query(ctx, userGetFiltered,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.Admin,
		arg.FilterAdmin,
		arg.FilterReal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGetFilteredRow
	for rows.Next() {
		var i UserGetFilteredRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Uid,
			&i.User.Name,
			&i.User.DisplayName,
			&i.User.AvatarUrl,
			&i.User.Crosshair,
			&i.User.Admin,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userUpdate = `-- name: UserUpdate :exec
UPDATE users
SET name = $2, display_name = $3, avatar_url = $4, crosshair = $5, admin = $6
WHERE id = $1
`

type UserUpdateParams struct {
	ID          int32
	Name        pgtype.Text
	DisplayName string
	AvatarUrl   pgtype.Text
	Crosshair   pgtype.Text
	Admin       bool
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) error {
	_, err := q.db.Exec(ctx, userUpdate,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Crosshair,
		arg.Admin,
	)
	return err
}
