// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const userGet = `-- name: UserGet :one
SELECT id, uid, name, display_name, email
FROM users
WHERE id = $1
`

func (q *Queries) UserGet(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}
